### ISSUE TITLE
Change GovNo to GovGen

### ISSUE THREAD

**Issue by ccomben** [atomone-hub/genesis#106]
[@jaekwon](https://github.com/jaekwon) Suggest changing the name 'GovNo' to 'GovGen' to better reflect the project’s dedication and values.

# Change AtomOne Governance-Only Chain 'GovNo' to 'GovGen'

The governance-only chain detailed in [issue 71](https://github.com/atomone-hub/genesis/issues/71) was proposed with the name 'GovNo' to express the inclusion of validators who voted 'NO' and 'NWV' on prop 848 to establish the Genesis of AtomOne. As slang for “shit” or "turd" in Slavic languages, the term “govno” appeared especially appropriate to convey that the GOVNO token is for governance and staking *only* and is not expected to have any monetary value, as stated:

> GOVNO cannot be transferred, sold, or given to another individual or entity, has no cash value, and cannot be redeemed for cash, credit, or any other item of value.

However, after hearing community feedback, it is also understandable that the 'GovNo' name may cause offense to some people and may prevent potential contributors from joining. It may also fail to accurately reflect the seriousness of AtomOne and the depth of the community’s commitment to it. 

This issue, therefore, proposes changing the name of 'GovNo' to 'GovGen'. While 'NO' and 'NWV' voters on prop 848 may not be so obviously reflected, the new name makes it clear that those voters who participate in the governance-only chain GovGen will be establishing the Genesis for AtomOne ('Gen'). Implicitly, the governance-only token should be changed to GOVGEN.

**Comment by jaekwon** [comment]
Yes, let's make it GovGen.
