### ISSUE TITLE
Airdrop ratio, Snapshot date, CEX support etc..

### ISSUE THREAD

**Issue by juwon-jin** [atomone-hub/genesis#15]
Nothing has been decided for sure regarding the ATOM1 split currently being discussed in X, but I would like to hear Jaekwon's plans or desired direction.

1. What is the airdrop rate for YES / NO / VETO / Abstain / new holders (holders who did not hold ATOM at the time of voting)?

2. When is the expected Snapshot date?

3. Will the CEX(binance, coinbase, upbit etc..) exchange request support for airdrops at the time of snapshot?

**Comment by FocSon** [comment]
Let's continue the discussion in one thread : https://github.com/atomone-hub/genesis/issues/18#issue-2014513676

**Comment by giunatale** [comment]
Thank you @FocSon, great to see community starting to self-moderate. Number of issues is increasing and information can be lost if there is redundancy.

As I also mentioned in the other post though, the discussion around distribution is being mainly held here: https://github.com/atomone-hub/genesis/issues/12

**Comment by jaekwon** [comment]
1. What is the airdrop rate for YES / NO / VETO / Abstain / new holders (holders who did not hold ATOM at the time of voting)?

Check this out: https://github.com/atomone-hub/genesis/issues/12#issuecomment-1831327478; Let's use #12 to discuss these parameters for YES/NO/etc.

3. For CEX... I think we should hold these tokens and make sure the exchanges agree to some things before we release them. Such as, to distribute them fairly, or not at all; and to make them agree to publish their addresses as CEX addresses, and to agree to allow us to reduce their voting power.
