### ISSUE TITLE
ATOM Trade mark infringement.

### ISSUE THREAD

**Issue by FarOutAndCosmic** [atomone-hub/genesis#58]
It appears ICF own the 'ATOM' trademark in the context of cosmos & blockchain etc. I believe this needs attention asap.

**Comment by FarOutAndCosmic** [comment]
Hard to believe something a ubiquitous as an atom can be trademarked... But there you go..

**Comment by jaekwon** [comment]
It's AtomOne, not Atom, and let's see. For me, my preference is that we go ahead and use AtomOne as the going project name, and rebrand if necessary down the line. This is a matter of community brand management, and it should be the goal of the ICF to foster competition AND cooperation by clarifying what the rules are. If it fails to make a good balance, it will only hurt $ATOM in the end. ATOM as a brand is strongest if it includes ATOM* split tokens. If it won't agree to it, then AtomOne's ecosystem will be the defacto split-generated ecosystem. ATONE? ;) 

AtomOne also already has precedent from the prior conversations around proposition 82. I just want whatever "AtomOne" is called, to be whatever is consistent in spirit with what I have already written. Nothing that conflicts with the general spirit should be called "AtomOne" arguably as a matter of common law.

**Comment by wnmnsr** [comment]
I agree, @jaekwon. 

While it is fundamentally important to ensure that AtomOne maintains a distinctive identity, it needs to be clear that it is a fork, as that in itself is part of the AtomOne identity.

As far as the name, AtomOne is a different name than Atom. It can also be argued that AtomOne is the name of the chain, while ATOM is the name of the ticker. 

AtomOne is not the same as Cosmos.

As far as the ticker goes, forks tend to preserve similar names/tickers than the chains they came from (see $BTC-similar tickers, see $ETH-similar tickers).

**Comment by common5ense** [comment]
I think @wnmnsr is splitting atoms here :) The distinction of "ICF's ATOM is for the ticker, but we are using it as the name of the Chain" won't really hold up in traditional legal systems - both chains "operate in the same industry, with similar offering and targeting the same customer base" - i.e. any reasonable person could confused the two, and so legal systems would side with the trademark holder. [my common-sense, im-not-a-lawyer view]

Please don't use "ATONE". Too much of a meme-factor.

@FarOutAndCosmic is right, in that this being a fork is a key part of the identity, and so, should be part of the brand identity. But we shouldn't do it in a way that just creates more contention and confusion.

imo, @jaekwon's reasons for forking - (as i summarize it, the better economic security model) - is a valid and justified reason for the fork to exist - in its own right as a better product and not just a meme token.

My suggestion would be to use "Cosmos Hub Classic" or "Cosmos Classic", and the ticker to be $GAIA [after all, gaia is what's being forked, and I don't think anyone has that trademarked]

**Comment by FarOutAndCosmic** [comment]
@common5ense I like where your going with the Cosmos Classic idea. $GAIA is already used as a ticker by Everworld though. I favour the idea of a move away from the word atom, not least as it's crowded with versions like STATOM, LATOM, HATOM etc etc.

**Comment by jaekwon** [comment]
> My suggestion would be to use "Cosmos Hub Classic" or "Cosmos Classic", and the ticker to be $GAIA [after all, gaia is what's being forked, and I don't think anyone has that trademarked]

For now, AtomOne is the working project name. If we cannot call our hub AtomOne, by that reasoning Cosmos Classic wouldn't work either. Ethereum Classic coins have ticker $ETC but the coins are still "ether". HongKong uses "dollars" but they are not the same as USD.
