### ISSUE TITLE
"Human-made" approach, no-AI commitment

### ISSUE THREAD

**Issue by wnmnsr** [atomone-hub/genesis#61]
On several threads there seems to be an underlying tension between favoring the use of AI for contributions and an opposition to such practices—the latter mainly from the project visionary @jaekwon. It's fully understandable how the use of AI can be a seemingly practical quick fix, but one with severe consequences over the long term. 

I suggest we, those in favor of building and contributing without the use of AI, commit to it publicly. This should not be a constraint for all (especially those who might not convinced about the harmfulness of AI), but just a public decision from those who refuse, to commit to human-made work. This issue pertains to a philosophy of work, an approach to how we contribute.

If this issue is out of place, please delete it.

**Comment by moul** [comment]
Thanks for your input. Please add it to the main AI issue (#39).

If you think your issue should stay separate, reopen it and explain why.
