### ISSUE TITLE
Create an awesome-atomone / community repo?

### ISSUE THREAD

**Issue by moul** [atomone-hub/genesis#70]
We should consider creating a repository similar to the community-driven "awesome-gno" on GitHub.

Could be:
- https://github.com/atomone-hub/community
- https://github.com/atomone-hub/awesome-atomeone
- https://github.com/atomone-hub/awesome-atone

We include a disclaimer stating that the content is community-generated/curated and unofficial. This repository would provide a space for community discussions, initiatives, recipes, and scripts. We can be less restrictive regarding AI limitations (#39) and use the Wiki feature instead of PRs for maintaining news and summaries. It would also make moderation more manageable by distributing the responsibility. Over time, it could reference new forks, important tweets, and more.

This would make the current repo stricter overall, while also allowing for more accessibility and other topics on the new one.

I believe that it's probably too early now and we should focus on pushing the limits of the current repo and wait for more foundations (especially the README), I believe this move will be important for scaling the initiative.

**Comment by jaekwon** [comment]
Ok, if we can limit AI usage to within a section within a repo, then sure. 
But only within those bounds, Jarvis.

**Comment by jaekwon** [comment]
We can start with an AWESOME.md file and see how it evolves.

**Comment by jaekwon** [comment]
closing for cleanup
