### ISSUE TITLE
Liquid staked ATONE

### ISSUE THREAD

**Issue by WaqarMMirza** [atomone-hub/genesis#81]
In the current model of Cosmos Hub liquid staking is not ideal, users forfeit not only the governance VP but also lose the right to stake with the validators they want to stake with. The projects that offer the LSDs redistribute the already distributed VP and concentrate it with the chosen validators.  

I would suggest tackling the situation on the ATONE protocol level with all corners covered.  One wishful thinking ia the introduction of multilevel Liquid Staking Tokens (LSTs). In this approach, each validator issues their unique LST. However, to streamline user experience and avoid confusion, all these LSTs would contribute to a unified pool and be converted into a single, universally recognized LST ( stATONE)

This approach aims to preserve the decentralization ethos, while providing users with the benefits of liquid staking.

**Comment by giunatale** [comment]
I suggest you look at #41

AtomOne will tackle liquid staking differently.

This is also discussed in the genesis readme, which I invite you to read carefully

**Comment by giunatale** [comment]
and for the record, it is actually better - in general - to limit the choice of the validator for liquid staking for security reasons (the Principal-Agent problem) and you absolutely don't want liquid staking tokens to have governance power. It's a governance takeover threat

**Comment by giunatale** [comment]
thanks a lot. Please don't hesitate to ask your questions in #12. 

in general, the idea on AtomOne anyway is that there will be a sanctioned method that is intended to minimize the systemic risks introduced with liquid staking as much as possible, and perhaps have some nice properties such as fixed or deflationary supply

The design of this liquid staking alternative is what is referred to as $PHOTON.

**Comment by WaqarMMirza** [comment]
I am educating thoroughly myself on the topic before making additional comments from economic perspective and It would be great if you could direct me to $PHOTON tokenomics/ graphical representation of the model.

**Comment by giunatale** [comment]
There isn't one. I understand it's a bit daunting to "understand" something for which the design and specs are still fuzzy.

I am suggesting you start by reading
https://github.com/atomone-hub/genesis/blob/main/README.md#role-as-atom-liquid-staking-provider
https://github.com/atomone-hub/genesis/blob/main/README.md#photon-the-more-deflationary-version-of-atone

and this previous writing from jae https://github.com/tendermint/atom_one/blob/c0f7d935930fedb700866c079a7056729e87d899/README.md#article-3c-the-photon-token

just the linked sections.

I also try to recap the fatures from my understanding in the first post of #41, except point 6 where I take it a little further.

I also suggest reading https://eprint.iacr.org/2023/605  for understanding classical liquid staking
and my comment here https://github.com/atomone-hub/genesis/issues/13#issuecomment-1836113106

Hope this helps. It's not perfect, but really the discussions around $PHOTON are barely getting started, this is all I am aware of that may be relevant.

**Comment by WaqarMMirza** [comment]
Thank you so much for the share, I hope to be helpful in $PHOTON some way.
