### ISSUE TITLE
Request for a validator repository 

### ISSUE THREAD

**Issue by VT-Cosmos** [atomone-hub/genesis#93]
@jaekwon - Suggesting a validator directory repository, in order to make it easier for the validators community to engage directly with one another, to coordinate upcoming tasks, and collaborate more efficiently. For this purpose I put together a draft for the Readme content below. 

----------

**Name of the repository: Validators
Description: Directory for GovNo and AtomOne Validators** 

The GovNo and AtomOne Validators directory is a space to build a registry of GovNo and AtomOne validators for the community. A comprehensive list of validators, with information on who they are and how to get in touch, will make it easier for the validators community to engage directly with one another, coordinate upcoming tasks, and collaborate more efficiently. This directory is also a great space to discuss validated proposals in regard to operating requirements, upcoming issues, implementation ideas, or proposed solutions.

All validators who have voted NO or NWV on CosmosHub proposal #848 are invited to submit their request for participation through a pull request to this repository. 

The Validators directory of the AtomOne repo is an initiative to help serve as a guide to:

- make it easier for existing projects, newcomers and community members to identify the approved validators
- for validators to coordinate on upcoming tasks and issues related to their operating activity as well as share valuable resource
- find development synergies and implementations
- make introductions to potential partners
- get plugged into the ecosystem

—--------------------------------------

**AtomOne Validator Application Template:**

Welcome. If you are a validator and would like to submit your application to join the AtomOne GovNo Validator Directory, please use this template to submit a pull request. 
You can tag it with "validators directory"

1. The name of your validator
2. Why you want to become a validator for GovNo and AtomOne
3. Brief history/ Intro to your validator
4. Details of your validator (website and contact email)
5. Team structure, roles, and Discord handles
6. Link to your main social accounts

**In order for the application to be approved by the community, all AtomOne/GovNo Validators:**

7. Must replicate, understand, and validate the genesis distribution. (See https://github.com/atomone-hub/genesis/pull/65#pullrequestreview-1775992431)
8. Must contribute to the above to prove understanding of it by contributing to the code or creating a PR/PRs 
9. Must adhere to a global decentralization mandate and if required to cooperate in translation for an efficient global reach
10. Must contribute to build a fair validators distribution structure by building guidelines to include tiers, participation levels, and validators limitations and operating conditions
11. Must provide Transparency disclosures of associations among validators. (Also see https://github.com/atomone-hub/genesis/issues/75). The AtomOne Community will put together best practices for KYC-ing and approving validator submissions. The conversation can be followed here: https://github.com/atomone-hub/genesis/issues/75

**Comment by ABCharlieEth** [comment]
There are 5 validators who weighted vote on 848. **GATA DAO** is one of those.  
https://dev.mintscan.io/cosmos/txs/5092603A846CF9C665057EA3BC65A81394F4974C6364FB6AF565FCA0CE67D9A3?height=18010454
![image](https://github.com/atomone-hub/genesis/assets/101841357/abdeaa73-c3ed-4ac2-87ec-620b5162d43a)
 
I respect the decision if @jaekwon thinks we shouldn't participate as validator, but I do believe we should be eligible as we are a DAO validator and represented what our community wanted "proportionately".

**Comment by 0xevolution** [comment]
@jaekwon Why not open to everyone? When it's not a competition (Atom vs AtomOne).
Should we have some route for Yes voting val/s that may be are aligned now with AtomOne? Or want to make more informed decision now? 
Whatever the reason, maybe as a result of definition/redefinition of constitution, true realization/awareness or anything.

**Comment by gin** [comment]
I think this issue (#93) can be closed now?

👍 Repository at https://github.com/atomone-hub/validator

**Comment by salmad3** [comment]
> I think this issue (#93) can be closed now?
> 
> 👍 Repository at https://github.com/atomone-hub/validator

Looks good. I believe it can be closed. Please reopen if otherwise.
