### ISSUE TITLE
Add AtomOne FAQ to the README

### ISSUE THREAD

**Issue by ccomben** [atomone-hub/genesis#94]
@jaekwon Suggest adding this FAQ to the Readme to point people to as their first source of answers to multiple questions.

# AtomOne FAQ

**There have been many questions from the community about AtomOne and GovGen across various platforms. This FAQ attempts to consolidate and answer most of them, but discussions are ongoing in the [repo](https://github.com/atomone-hub/genesis/issues). You can join an existing discussion by clicking on “Issues,” selecting the topic that interests you, and adding your comment, or you can open a new discussion by starting a new Issue or creating a Pull Request. Also, if you would like to add to this effort, please submit a PR with your contribution. You can also join the unofficial [AtomOne Discord](https://discord.com/invite/atomone) channel and contribute to the conversation there.**

**Q: What is AtomOne, and how does it benefit the Cosmos community?**

A: AtomOne is a branch of Gaia that complements the broader Cosmos ecosystem with a security-conscious alternative hub. AtomOne recommits to the founding vision of the Cosmos Hub as a minimal IBC/ICS hub secured by a staking token targeting two-thirds of the stake bonded. AtomOne contributors uphold the original values of the Cosmos Hub—security, sustainability, decentralization—and agree that hub minimalism enforced by a written constitution is the only way to ensure financial security and scale to billions of people.

AtomOne’s tokenomics, core shards, growth plan, and responsibilities align with a true minimal hub. Smart contract systems and VMs do not live on the Hub but on consumer shard chains to preserve utmost security and efficiency. AtomOne solves the scaling of transaction throughput using an optimized version of ICS (scaled security) where the validator sets are implicit for fast inter-hub communication without sacrificing independent BFT consensus layers.

**Q: What is ATONE, and how does it differ from ATOM?**

A: ATONE is a staking token, as originally intended for ATOM. ATONE will maintain the ⅔ majority staked target to ensure the security of the AtomOne chain. AtomOne contributors align highly with the vision as a minimal IBC-token-pegging and ICS hosting hub and that the ATONE token must never become a monetary token, as prop 848 does to ATOM.

**Q: Does AtomOne offer insurance against a Cosmos Hub failure?**

A: The passing of 848 presents manifold risks to the Cosmos Hub and ATOM token, which can be read in detail in an [AIB blog post here](https://allinbits.com/blog/nwv-to-prop-848-atom-must-not-be-money/). AtomOne re-commits to the original vision and primary mission of Cosmos Hub and provides a more security-conscious alternative to the Cosmos Hub.

**Q: What does AtomOne mean for the original Cosmos Hub?**

A: AtomOne does not compete with the Cosmos Hub but offers a bridge to make it more secure while implementing improved technical designs to guide Cosmos Hub’s future development. AtomOne contributors may also be contributors to the Cosmos Hub that align with the need for greater security, acting as a political party that advocates for steering the Hub toward making safer decisions. While AtomOne preserves hub minimalism, the AtomOne ecosystem will support innovative solutions such as liquid staking and smart contract systems deployed on ICS-secured shard chains.

**Q: When will AtomOne launch?**

A: There is no definitive timeline for the launch of AtomOne yet, as this will depend on community involvement and willingness to support the new chain. However, the software is already available and can be iterated over time to launch the AtomOne chain quickly. To ensure alignment throughout the creation of AtomOne and assess the sentiments of NO and NVW voters on prop 848, we propose launching a governance-only chain first, GovGen. GovGen will enable the completion of the repository, preparation of the documentation in a decentralized and fair way, and establishment of the Genesis for AtomOne (more on GovGen below). 

**Q: How can I contribute to AtomOne?**

A: Anyone can contribute to AtomOne, as it is a community-driven initiative and the decision-making process is collaborativе. If you understand the importance of hub minimalism for security and sustainability, join the movement. If you would like to contribute, sign up for a GitHub account (if you don’t already have one) and head over to the [AtomOne repo](https://github.com/orgs/atomone-hub/repositories). You can join an existing discussion by clicking on “Issues,” selecting the topic that interests you, and adding your comment, or you can open a new discussion by starting a new Issue or creating a Pull Request. 

Alternatively, you can join the unofficial [AtomOne Discord](https://discord.com/invite/atomone) channel and contribute to the conversation there.

**Q: Is AtomOne the final name of the new chain?**

A: The AtomOne name is a placeholder pending the community’s input and discussions.

**Q: Is $ATONE the ticker symbol?**

A: Discussions are ongoing about the ticker symbol, and there is an open issue in the repo ([#63](https://github.com/atomone-hub/genesis/issues/63)). As it stands, $ATONE is the agreed-upon ticker symbol for AtomOne. If you have another idea, you are welcome to comment on the conversation.

**Q: How will the tokens be distributed?** 

A: The distribution method is an ongoing discussion in [issue #12](https://github.com/atomone-hub/genesis/issues/12). As it stands, ATONE tokens will be mainly distributed to those who voted ‘NO’ or ‘NWV’ on prop 848 and are aligned with the vision of ATOM as a staking token. The ICF will be excluded from the distribution, and instead, 10% of the final amount will be allocated to contributors and on-chain DAOs. 10% of ATONEs will be premined for various purposes (such as pre-launch contributors and early adopters, IBC contributions, ICS contributors, etc.).

**Q: How much will I be slashed for voting YES on Prop 848?**

A: In principle, all ‘YES’ votes on #848 will be slashed, as their decision does not align with the values of the new chain, which focuses on ATONE's intrinsic value as a staking token rather than a monetary token. However, there could be a small distribution made to ‘YES’ voters, as the details of the airdrop distribution are still being discussed (join the discussion on the repo). The final decision of what Genesis will look like will be taken by the community and voted on through the GovGen chain. 

**Q: Will I be excluded for not voting on Prop 848?**

A: Airdrop distribution is still up for discussion on the repo, but non-voters will likely be included in the distribution. We want AtomOne to give concessions to Gaia and support it without being competitive or discriminatory. One such concession may be allowing liquid stakers to earn ATONE from staking ATOMs on AtomOne. These questions should be discussed and answered by the GovGen chain. 

**Q: Will I receive an airdrop for my ATOM if they are locked/LP’d/liquid staked/etc. ?**

A: Airdrop distribution discussion is ongoing, but liquid-staked, LP’d, and locked ATOM could be included in the distribution. The community must agree and do the legwork to track the tokens.

**Q: Do NO and NWV votes carry the same weight?**

A: Airdrop distribution is tentative and up for discussion on the repo, but NWV may be weighed heavier than NO.

**Q: Is there a distribution snapshot?**

A: The initial distribution snapshot will likely be taken from the final results of prop 848 (and possibly Prop 82). Those who voted ‘NO’ or ‘NWV’ will automatically be added to the airdrop distribution list with a future calculation of the amount. The snapshot for the GovGen chain will be taken immediately after the closing vote on 848.

**Q: When will the airdrop be?**

A: The airdrop will happen when all the work is completed and the chain is live. 

**Q: How can I buy the new ATONE token outside the airdrop?**

A: ATONE will likely be available on the open market (exchanges) after launch. Contributors seeking ATONE tokens who were not holding ATOM tokens at the time of the snapshot can be compensated for meaningful contributions to the repo.

**Q: How can I become a validator on AtomOne?** 

A: AtomOne will use a Proof-of-Stake delegation system similar to Cosmos Hub with some modifications to fix validator incentives and ensure that validators are paid more fairly and evenly. The incentive system is still a work in progress on the repo. However, priority will be given to validators who voted ‘NO’ and ‘NWV’ on Prop 848.

**Q: How do we encourage developer activity on the platform, and how do we fund the development of the chain?**

A: The initial premine will reserve funds for development, and the transaction fees will fund developers. Ideally, AtomOne will support DAO systems and smart contracts that specify how much developers are getting paid and for what. Everything should be recorded transparently and on-chain. GovGen should be used to figure out the scope of AtomOne and define what is and is not allowed in the AtomOne constitution. 

**Q: What is the incentive for validators to contribute early in GovGen? Will they be rewarded with incentives on AtomOne?**

A: Early contributors have historically been rewarded by the chain, and some incentives for participation could make sense. However, we don’t want to draw in the wrong set of validators more motivated by the money than the idea. 

**Q: If we slash the validators who voted YES, how do we secure additional validators to ensure the chain is decentralized?**

A: AtomOne will be community-driven, with opportunities for new validators that align with the chain’s vision. People who contribute meaningfully to the AtomOne repo will have opportunities to earn tokens and spin up a node if they are willing and aligned with the new chain’s values. AtomOne intends to fix validator incentives so that validators are incentivized to secure ICS consumer chains and hub shards through a constitutional economic model, where every validator is paid to run these services. 

**Q: What is the plan for scaling AtomOne?**
 
A: AtomOne solves the scaling of transaction throughput using an optimized version of ICS (scaled security) where the validator sets are implicit for fast inter-hub communication without sacrificing independent BFT consensus layers.

**Q: Will AtomOne use Cosmos Hub’s shared security?**

A: AtomOne hub will have its own ICS model (scaled security), a modified and optimized version of ICS1. 

**Q: Is there a possibility of AtomOne and Cosmos Hub providing security to each other through mesh security?**

A: This could be a possibility in the future. However, mesh security is still a developing technology and is something to consider at a later date.

**Q: What is GovGen?**

A: GovGen is a governance-only chain proposed as an independent component of AtomOne Genesis. The proposed token, GOVGEN, is only for governance (and staking for governance). This chain software is proposed as a fork of cosmoshub4 with minimal modifications; for example, SendTx will be disabled for GOVGEN. GOVGEN cannot be transferred, sold, or given to another individual or entity. It has no cash value and cannot be redeemed for cash, credit, or any other item of value. 

GovGen is not intended to be the main AtomOne chain. It is intended only for the purposes of assessing the sentiments of the NO and NWV voters on Prop #848, which was the defining proposition for the branch and the genesis of AtomOne. GovGen will enable the community to assess the support for AtomOne and discuss the next steps.

**Q: Who can take part in GovGen?**

A: The criteria for inclusion in this governance set is simply those who voted NO and NWV on Prop 848. NoWithVeto voters will not be given a bonus for their veto for the purpose of the AtomOne GovGen chain. GovGen will not be the governance for AtomOne but will bootstrap the requirements and definitions of the new chain. 

**Q: How will the voting system work?**

A: We should start as simply as possible with minimal modifications to Cosmos Hub and not require new tooling (which could present a point of vulnerability) to be able to use the system. This will allow us to be more agile and run the chain faster. We could use the Gaia CLI to sign transactions and Cosmos wallets Keplr and Leap. We can make some minor tweaks to the governance module, to increase the governance duration, maybe to even include an infinite duration so that votes can be changed at any time. All these issues will be discussed on the GovGen chain. 

We suggest increasing the threshold of proposals passing from 51% to 67% and holding off on making decisions without at least ⅔ majority on proposals. This will ensure that the decisions taken are safer and that there is no sizable vehement opposition that tries to sabotage the chain or affect consensus. Even after decisions are taken on GovGen, they should not be considered set in stone but may be subject to change.

**Q: How will the distribution of GovGen happen? Will it be equally distributed to all wallets that voted NO, or will it be prorated according to stake?**

A: This is a Proof of Stake system, so we will distribute according to stake, especially to avoid distributing to dust/bot accounts. NWV will not receive additional rewards from NO voters. ABSTAIN voters will not be included in GovGen, but they will receive rewards (proportionately slashed to what the actual distribution of YES versus NO was for that proposal) on AtomOne.

**Q: Should wallets that have not directly voted but delegated to their validators be included in the GovGen token distribution?**

A: Yes. We don’t want to punish people who did not vote because they agreed with their validator’s vote. In fact, the system was designed so that individuals do not have to vote but can delegate their votes. If we want to include this stipulation in the governance that individuals should actively vote, we should introduce it beforehand and not afterward. Let’s hold a poll to see how the community feels about this.

**Q: How about wallets with multiple validators, including validators that voted YES?**

A: If we introduce too many penalties, we risk reducing the participation in GovGen and being unable to reach quorum on proposals. Moreover, the YES votes are already excluded from the GovGen chain, and this part of the vote has already been considered.

**Q: What kind of support will validators be offered for supporting AtomOne and GovGen?**

A:  We believe that validators should receive more or less equitable payment to ensure fairness and make sure that smaller validators are able to work and new validators can get started and ramp up and be paid according to the work they put in and how many shards they are running. Incentives and disincentives need to be baked into the reward system to make sure this happens. The discussion is ongoing, and you can read more about validator incentives in the AtomOne repo.

**Q: Should we count validator delegations for GovGen or only the voters who explicitly voted?**

A: Since there was no prior agreement that non-voters (who otherwise inherit their validator's votes) would ever be punished, we should not exclude them. We would significantly dilute participation by excluding the stakers who inherited their validators' votes. However, perhaps governance votes on GovGen could pass both modes of tallying (with and without delegations) so that validators can also agree to the changes proposed as well as the stakers. This discussion is ongoing in [issue #71](https://github.com/atomone-hub/genesis/issues/71#issuecomment-1859281531).

**Q: Will GOVGEN tokens be transferable?**

A: SendTx will be disabled for GOVGEN. GOVGEN cannot be transferred, sold, or given to another individual or entity. It has no cash value and cannot be redeemed for cash, credit, or any other item of value. 

**Q: How will you prevent spam governance proposals on the GovGen chain?**

A: We propose setting a very high deposit limit for the proposals to prevent spamming. If a proposal is rejected with more than ⅓ voting NWV, we suggest the deposit be considered for slashing for any relevant future Genesis distribution. Furthermore, if the NO and NWV voters judge an account to be spamming, the spammer’s tokens in any relevant future Genesis distribution may be subject to slashing.

**Q: How will the GovGen chain be secure?**

A: AiB has volunteered to provide recommendations about Genesis software readiness, along with publishing and auditing procedures. However, this should not be the only source of information, especially as this is a decentralized process. Nothing that hasn’t already been used and audited will be used for the GovGen chain.

**Q: Can we use DAO DAO for the GovGen chain?**

A: As we are using a staking token, we plan to deploy a PoS GovGen chain in collaboration with validators, in line with the proposed practices. Exploring the use of DAO DAO is also an option, subject to community interest.

**Q: Can you clarify the concept of Hub Minimalism?**

A: Hub Minimalism is discussed in depth on [GitHub here](https://github.com/decentralists/DAO/tree/main/cosmoshub). In a nutshell, the key to durability and scalability is minimal implementation. Just as Bitcoin does one thing well (reliably transferring value between parties), AtomOne will focus on doing one thing well: acting as a security provider that is dependable and reliable for multi-token IBC pegging, keeping the attack vector on the Hub as small as possible.

**Comment by salmad3** [comment]
Let's add to the FAQ document that is initiated [here](https://github.com/atomone-hub/genesis/pull/92).
